// ============================================================
// export.js  --  Export schedule to PDF, DOCX, and Excel
// Uses jsPDF, docx (npm), and SheetJS libraries (loaded via CDN)
// ============================================================

// ---------- EXPORT TOOL AVAILABILITY ----------

function showExportUnavailable(format) {
  alert(`${format} is temporarily unavailable because its export library did not load. Please refresh the page and try again, or use another export format.`);
}

// ---------- PDF EXPORT ----------

function exportPDF() {
  if (!AppState.schedule) return alert("No schedule to export.");
  if (!window.jspdf || !window.jspdf.jsPDF) return showExportUnavailable("PDF export");

  // jsPDF is loaded from CDN
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const margin = 15;
  let y = margin;

  const majorReqs = AppState.validation?.majorReqs || CS_BA_REQUIREMENTS;

  // Title
  doc.setFontSize(18);
  doc.setTextColor(0, 60, 108); // UCSC blue
  doc.text("UCSC Academic Schedule Plan", margin, y);
  y += 10;

  // Subtitle
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(`${majorReqs.name} | Generated ${new Date().toLocaleDateString()}`, margin, y);
  y += 8;

  // Validation summary
  const v = AppState.validation;
  if (v) {
    doc.setFontSize(10);
    doc.setTextColor(v.allMet ? 40 : 180, v.allMet ? 120 : 40, 40);
    doc.text(v.allMet
      ? "Status: All requirements met"
      : "Status: Some requirements not yet fulfilled", margin, y);
    y += 6;
    doc.setTextColor(80, 80, 80);
    doc.text(`Total Units: ${v.totalUnits} / ${majorReqs.totalUnitsRequired}`, margin, y);
    y += 10;
  }

  // Schedule table
  for (const yearData of AppState.schedule) {
    // Check page break
    if (y > 250) { doc.addPage(); y = margin; }

    doc.setFontSize(13);
    doc.setTextColor(0, 60, 108);
    doc.text(`${yearData.label} (${yearData.academicStart}-${yearData.academicStart + 1})`, margin, y);
    y += 7;

    const quarterKeys = Object.keys(yearData.quarters);

    for (const q of quarterKeys) {
      const courses = yearData.quarters[q];
      if (courses.length === 0) continue;

      if (y > 260) { doc.addPage(); y = margin; }

      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      doc.setFont(undefined, "bold");
      doc.text(`${QUARTER_LABELS[q] || q}`, margin + 2, y);
      y += 5;

      doc.setFont(undefined, "normal");
      doc.setFontSize(9);

      for (const code of courses) {
        const course = COURSES[code];
        const title = course ? course.title : "Unknown";
        const units = course ? course.units : "?";
        const ge = course && course.ge ? ` [${course.ge}]` : "";

        doc.text(`  ${code} - ${title} (${units} cr)${ge}`, margin + 4, y);
        y += 4.5;

        if (y > 280) { doc.addPage(); y = margin; }
      }

      y += 3;
    }

    y += 5;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by UCSC Course Selection Automation. Please verify on the official UCSC catalog.", margin, 285);

  doc.save("UCSC_Schedule_Plan.pdf");
}


// ---------- EXCEL EXPORT ----------

function exportExcel() {
  if (!AppState.schedule) return alert("No schedule to export.");
  if (typeof XLSX === "undefined" || !XLSX.utils || !XLSX.writeFile) return showExportUnavailable("Excel export");

  // SheetJS (XLSX) is loaded from CDN
  const wb = XLSX.utils.book_new();

  const majorReqs = AppState.validation?.majorReqs || CS_BA_REQUIREMENTS;

  // Build schedule data
  const data = [
    ["UCSC Academic Schedule Plan"],
    [`${majorReqs.name} | Generated ${new Date().toLocaleDateString()}`],
    [],
    ["Year", "Quarter", "Course Code", "Course Title", "Units", "GE Code", "Requirement"]
  ];

  for (const yearData of AppState.schedule) {
    for (const [q, courses] of Object.entries(yearData.quarters)) {
      for (const code of courses) {
        const course = COURSES[code];
        data.push([
          yearData.label,
          QUARTER_LABELS[q] || q,
          code,
          course ? course.title : "Unknown",
          course ? course.units : 0,
          course && course.ge ? course.ge : "",
          course ? course.section.map(s => (SECTION_COLORS[s] || {}).label || s).join(", ") : ""
        ]);
      }
    }
  }

  // Add requirements summary sheet
  data.push([], [], ["=== REQUIREMENT STATUS ==="]);

  const v = AppState.validation;
  if (v) {
    data.push(["Total Units", `${v.totalUnits} / ${majorReqs.totalUnitsRequired}`, v.totalUnitsMet ? "MET" : "NOT MET"]);
    data.push(["Upper Division Units", `${v.upperDivUnits} / ${majorReqs.minUpperDivUnits}`, v.upperDivMet ? "MET" : "NOT MET"]);
    data.push([]);

    data.push(["--- Major Requirements ---"]);
    v.major.forEach(r => {
      data.push([r.name, r.fulfilled ? "MET" : "NOT MET", (r.selectedCourses || []).join(", ")]);
    });

    data.push([], ["--- General Education ---"]);
    v.ge.forEach(r => {
      data.push([r.name, r.fulfilled ? "MET" : "NOT MET", (r.courses || []).join(", ")]);
    });

    data.push([], ["--- UC Requirements ---"]);
    v.uc.forEach(r => {
      data.push([r.name, r.fulfilled ? "MET" : "NOT MET", (r.courses || []).join(", ")]);
    });
  }

  const ws = XLSX.utils.aoa_to_sheet(data);

  // Set column widths
  ws["!cols"] = [
    { wch: 12 }, { wch: 10 }, { wch: 14 }, { wch: 45 },
    { wch: 6 }, { wch: 8 }, { wch: 20 }
  ];

  XLSX.utils.book_append_sheet(wb, ws, "Schedule");
  XLSX.writeFile(wb, "UCSC_Schedule_Plan.xlsx");
}


// ---------- DOCX EXPORT ----------

function exportDOCX() {
  if (!AppState.schedule) return alert("No schedule to export.");
  if (!window.docx || !window.docx.Document || !window.docx.Packer) return showExportUnavailable("Word export");

  const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
          AlignmentType, WidthType, BorderStyle, ShadingType } = window.docx;

  const majorReqs = AppState.validation?.majorReqs || CS_BA_REQUIREMENTS;
  const children = [];

  // Title
  children.push(new Paragraph({
    children: [new TextRun({ text: "UCSC Academic Schedule Plan", bold: true, size: 36, color: "003C6C" })],
    spacing: { after: 200 }
  }));

  children.push(new Paragraph({
    children: [new TextRun({ text: `${majorReqs.name} | Generated ${new Date().toLocaleDateString()}`, size: 22, color: "666666" })],
    spacing: { after: 400 }
  }));

  // Validation status
  const v = AppState.validation;
  if (v) {
    children.push(new Paragraph({
      children: [new TextRun({
        text: v.allMet ? "Status: All requirements met" : "Status: Some requirements not yet fulfilled",
        bold: true, size: 22, color: v.allMet ? "28a745" : "dc3545"
      })],
      spacing: { after: 100 }
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: `Total Units: ${v.totalUnits} / ${majorReqs.totalUnitsRequired}`, size: 20 })],
      spacing: { after: 300 }
    }));
  }

  // Schedule by year
  for (const yearData of AppState.schedule) {
    children.push(new Paragraph({
      children: [new TextRun({ text: `${yearData.label} (${yearData.academicStart}-${yearData.academicStart + 1})`, bold: true, size: 28, color: "003C6C" })],
      spacing: { before: 300, after: 200 }
    }));

    for (const [q, courses] of Object.entries(yearData.quarters)) {
      if (courses.length === 0) continue;

      children.push(new Paragraph({
        children: [new TextRun({ text: QUARTER_LABELS[q] || q, bold: true, size: 22 })],
        spacing: { before: 100, after: 100 }
      }));

      // Create a table for this quarter's courses
      const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
      const borders = { top: border, bottom: border, left: border, right: border };

      const headerRow = new TableRow({
        children: [
          new TableCell({ borders, shading: { fill: "003C6C", type: ShadingType.CLEAR },
            children: [new Paragraph({ children: [new TextRun({ text: "Course", bold: true, color: "FFFFFF", size: 18 })] })],
            width: { size: 1500, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
          new TableCell({ borders, shading: { fill: "003C6C", type: ShadingType.CLEAR },
            children: [new Paragraph({ children: [new TextRun({ text: "Title", bold: true, color: "FFFFFF", size: 18 })] })],
            width: { size: 5000, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
          new TableCell({ borders, shading: { fill: "003C6C", type: ShadingType.CLEAR },
            children: [new Paragraph({ children: [new TextRun({ text: "Units", bold: true, color: "FFFFFF", size: 18 })] })],
            width: { size: 800, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
          new TableCell({ borders, shading: { fill: "003C6C", type: ShadingType.CLEAR },
            children: [new Paragraph({ children: [new TextRun({ text: "GE", bold: true, color: "FFFFFF", size: 18 })] })],
            width: { size: 800, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
        ]
      });

      const rows = [headerRow];
      for (const code of courses) {
        const course = COURSES[code];
        const rowShading = rows.length % 2 === 0 ? "F5F5F5" : "FFFFFF";
        rows.push(new TableRow({
          children: [
            new TableCell({ borders, shading: { fill: rowShading, type: ShadingType.CLEAR },
              children: [new Paragraph({ children: [new TextRun({ text: code, bold: true, size: 18 })] })],
              width: { size: 1500, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
            new TableCell({ borders, shading: { fill: rowShading, type: ShadingType.CLEAR },
              children: [new Paragraph({ children: [new TextRun({ text: course ? course.title : "Unknown", size: 18 })] })],
              width: { size: 5000, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
            new TableCell({ borders, shading: { fill: rowShading, type: ShadingType.CLEAR },
              children: [new Paragraph({ children: [new TextRun({ text: `${course ? course.units : "?"}`, size: 18 })] })],
              width: { size: 800, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
            new TableCell({ borders, shading: { fill: rowShading, type: ShadingType.CLEAR },
              children: [new Paragraph({ children: [new TextRun({ text: course && course.ge ? course.ge : "-", size: 18 })] })],
              width: { size: 800, type: WidthType.DXA }, margins: { top: 40, bottom: 40, left: 80, right: 80 } }),
          ]
        }));
      }

      children.push(new Table({
        rows,
        width: { size: 8100, type: WidthType.DXA },
        columnWidths: [1500, 5000, 800, 800]
      }));
    }
  }

  // Footer
  children.push(new Paragraph({
    children: [new TextRun({ text: "\nGenerated by UCSC Course Selection Automation. Please verify on the official UCSC catalog.", size: 16, color: "999999", italics: true })],
    spacing: { before: 600 }
  }));

  const docFile = new Document({
    sections: [{ children }]
  });

  Packer.toBlob(docFile).then(blob => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "UCSC_Schedule_Plan.docx";
    a.click();
    URL.revokeObjectURL(url);
  });
}
